### ISSUE TITLE
Question: -bash: a11y-sitechecker: command not found

### ISSUE THREAD

**Issue by mhanzouti** [forsti0506/a11y-sitechecker#58]
Hello
Sorry, I'm a newbie with npm.
I pulled the code in this repo and run npm install and yarn add.
But when I wanted to run a11y-sitechecker through command line it throws me the following message:
-bash: a11y-sitechecker: command not found
Please advice.
Thanks,
M

**Comment by forsti0506** [comment]
Hi,

maybe it was a bit misundestanding, but you can use it with yarn or npm (this are 2 different package managers).

The workflow for you would be something like:

- create a new folder
- npm init
- npm install a11y-sitechecker
- a11y-sitechecker https://www.test.at --config=config.json -T=1000

If this is not working, please provide more information: Where are you running it? Whats your workflow?

Thanks and have a nice day!

**Comment by jurjendevries** [comment]
Hi, I have the same issue.
From Ubuntu 20.04 LTS I did the following from the readme:
$ npm install a11y-sitechecker | yarn add a11y-sitechecker

i got:
Command 'yarn' not found, but can be installed with:

apt install cmdtest

so I did

$ apt install cmdtest

I tried it again and got:

00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'add'
npm WARN saveError ENOENT: no such file or directory, open '/root/a11y-sitechecker/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/root/a11y-sitechecker/package.json'
npm WARN a11y-sitechecker No description
npm WARN a11y-sitechecker No repository field.
npm WARN a11y-sitechecker No README data
npm WARN a11y-sitechecker No license field.

when I run it from the command line
$ a11y-sitechecker https://www.google.com
I got
a11y-sitechecker: command not found

When I run npm from the command line I got:
package name: (a11y-sitechecker) npm install a11y-sitechecker
Sorry, name can only contain URL-friendly characters.

I guess I am misunderstanding something. I am very curious to this tool. Thanks for helping in advance.

**Comment by forsti0506** [comment]
Maybe as a clarification

There are 2 different things: If you checkout the github code of this you can change the source code!

If you like to use the tool, you have to get your own npm repository (or you have an existing one) with npm init in an empty folder!

And then you can install it with npm install a11y-sitechecker!

Example from me:

![image](https://user-images.githubusercontent.com/38582064/115972931-b86cbc80-a551-11eb-8875-94af6cfb8827.png)


Best regards

**Comment by mhanzouti** [comment]
> Hi,
> 
> maybe it was a bit misundestanding, but you can use it with yarn or npm (this are 2 different package managers).
> 
> And you don't have to pull the code, if you don't want to change the tool itself. The tool can be used with npm alone, you installed the tool as a dependency in the tool.
> 
> The workflow for you would be something like:
> 
> * create a new folder
> * npm init
> * npm install a11y-sitechecker
> * a11y-sitechecker https://www.test.at --config=config.json -T=1000
> 
> If this is not working, please provide more information: Where are you running it? Whats your workflow?
> 
> Thanks and have a nice day!

Hi @forsti0506 
Thanks for the reply.
I followed your steps but I still have the same issue:
```
MacBookPro:Dev $ mkdir a11y-cheker
MacBookPro:Dev $ cd a11y-cheker/
MacBookPro:a11y-cheker $ npm init
This utility will walk you through creating a package.json file.
It only covers the most common items and tries to guess sensible defaults.

See `npm help init` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
package name: (a11y-cheker) 
version: (1.0.0) 
description: 
entry point: (index.js) 
test command: testinger
git repository: no
keywords: sds
author: Moez
license: (ISC) 
About to write to /Users/Documents/Dev/a11y-cheker/package.json:

{
  "name": "a11y-cheker",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "testinger"
  },
  "repository": {
    "type": "git",
    "url": "no"
  },
  "keywords": [
    "sds"
  ],
  "author": "Moez Hanzouti",
  "license": "ISC"
}


Is this OK? (yes) y
MacBookPro:a11y-cheker $ npm install a11y-sitechecker
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 175 packages, and audited 176 packages in 13s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
MacBookPro:a11y-cheker $ a11y-sitechecker https://www.yahoo.com —config=config.json -T=1000
-bash: a11y-sitechecker https://www.yahoo.com: No such file or directory
```

PS: I'm working on my local machine a Mac with Catalina 10.15.7.

Thanks for your help.
Cheers

**Comment by forsti0506** [comment]
Maybe it would be possible to call the script directly in your workspace root folder (in your case a11y-checker:

`node node_modules/a11y-sitechecker/bin/a11y-sitechecker.js https://www.test.de --config=configohnedb.json --threshold=1000`

Best regards
